server.port: 8085
spring.datasource:
  driverClassName: 'org.hibernate.dialect.PostgreSQLDialect'
  url: 'jdbc:postgresql://localhost:5432/postgres'
  username: 'postgres'
  password: 'admin1234'

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update

spring.flyway:
  baselineOnMigrate: true
  locations: src/main/resources/db/migration